export default function TermsPage() {
  return (
    <div style={styles.page}>
      <div style={styles.container}>
        <div style={styles.header}>
          <a href="/" style={styles.back}>&#8592; Back</a>
          <div style={styles.brand}>
            <div style={styles.dot} />
            <span style={styles.brandName}>FitCoach</span>
          </div>
        </div>

        <h1 style={styles.title}>Terms of Service</h1>
        <p style={styles.meta}>Last updated: March 2026</p>

        <div style={styles.divider} />

        <Section title="1. Acceptance of Terms">
          By accessing or using FitCoach, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service. We reserve the right to update these terms at any time, and continued use of the service constitutes acceptance of any changes.
        </Section>

        <Section title="2. Description of Service">
          FitCoach is an AI-powered fitness coaching platform that provides personalized workout plans, nutrition guidance, exercise tips, and general fitness advice through a conversational interface. The service is powered by large language models and may include AI-generated images and curated video resources.
        </Section>

        <Section title="3. Not Medical Advice">
          <strong style={{ color: "#00ff88" }}>Important:</strong> FitCoach is not a medical service. All content provided by FitCoach, including workout plans, nutrition advice, and health information, is for general informational and educational purposes only. It does not constitute medical advice, diagnosis, or treatment.
          <br /><br />
          Always consult a qualified healthcare professional or licensed physician before starting any new exercise program, making significant dietary changes, or if you have any health conditions, injuries, or concerns. Do not disregard professional medical advice based on anything you read or receive from FitCoach.
        </Section>

        <Section title="4. User Accounts">
          You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must be at least 16 years old to use this service. We reserve the right to suspend or terminate accounts that violate these terms.
        </Section>

        <Section title="5. Acceptable Use">
          You agree not to:
          <ul style={styles.list}>
            <li>Use the service for any unlawful purpose</li>
            <li>Attempt to gain unauthorized access to any part of the service</li>
            <li>Submit false, misleading, or harmful content</li>
            <li>Reverse engineer, copy, or redistribute any part of the service</li>
            <li>Use the service in a way that could harm other users or third parties</li>
          </ul>
        </Section>

        <Section title="6. AI-Generated Content">
          Responses from FitCoach are generated by artificial intelligence and may not always be accurate, complete, or up to date. AI-generated images are created by third-party services and are for illustrative purposes only. We do not guarantee the accuracy of any AI-generated content and encourage you to verify important information with qualified professionals.
        </Section>

        <Section title="7. Intellectual Property">
          All software, design, and content on FitCoach (excluding user-submitted content) is the property of FitCoach and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without our prior written consent.
        </Section>

        <Section title="8. Limitation of Liability">
          To the fullest extent permitted by law, FitCoach and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of data, personal injury, or any harm resulting from your use of or inability to use the service. Your use of FitCoach is entirely at your own risk.
        </Section>

        <Section title="9. Termination">
          We reserve the right to suspend or terminate your access to FitCoach at any time, for any reason, without notice. You may also delete your account at any time by contacting us or using the account settings.
        </Section>

        <Section title="10. Contact">
          If you have any questions about these Terms of Service, please contact us through the app or at the email address provided in your account settings.
        </Section>

        <div style={styles.divider} />
        <p style={styles.footer}>These terms are effective as of March 2026 and apply to all users of FitCoach.</p>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: "32px" }}>
      <h2 style={{
        fontSize: "14px",
        fontWeight: 700,
        color: "#00ff88",
        letterSpacing: "0.04em",
        marginBottom: "10px",
        fontFamily: "var(--font-space-mono), monospace",
        textTransform: "uppercase",
      }}>{title}</h2>
      <div style={{
        fontSize: "14px",
        color: "rgba(235,235,235,0.7)",
        lineHeight: 1.8,
        fontFamily: "var(--font-syne), sans-serif",
      }}>{children}</div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100dvh",
    background: "#080808",
    padding: "40px 24px 80px",
    fontFamily: "var(--font-syne), sans-serif",
  },
  container: {
    maxWidth: "680px",
    margin: "0 auto",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "48px",
  },
  back: {
    fontSize: "12px",
    color: "rgba(235,235,235,0.4)",
    textDecoration: "none",
    fontFamily: "var(--font-space-mono), monospace",
    letterSpacing: "0.06em",
    transition: "color 0.15s",
  },
  brand: { display: "flex", alignItems: "center", gap: "8px" },
  dot: {
    width: "8px", height: "8px", borderRadius: "50%", background: "#00ff88",
    boxShadow: "0 0 8px #00ff88",
  },
  brandName: {
    fontSize: "16px", fontWeight: 700, color: "#ebebeb",
    fontFamily: "var(--font-syne), sans-serif",
  },
  title: {
    fontSize: "32px",
    fontWeight: 800,
    color: "#ebebeb",
    letterSpacing: "-0.02em",
    marginBottom: "8px",
  },
  meta: {
    fontSize: "11px",
    color: "rgba(235,235,235,0.3)",
    fontFamily: "var(--font-space-mono), monospace",
    letterSpacing: "0.06em",
    marginBottom: "0",
  },
  divider: {
    height: "1px",
    background: "rgba(255,255,255,0.06)",
    margin: "32px 0",
  },
  list: {
    margin: "10px 0 0 0",
    paddingLeft: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  footer: {
    fontSize: "11px",
    color: "rgba(235,235,235,0.2)",
    fontFamily: "var(--font-space-mono), monospace",
    lineHeight: 1.7,
    textAlign: "center",
  },
};
